[phases.setup]
nixPkgs = ["dotnet-sdk_8_0", "nodejs_20"]

[phases.install]
cmds = [
  "cd beauty-salon-frontend && npm install",
  "cd BeautySalonAPI && dotnet restore"
]

[phases.build]
cmds = [
  "cd beauty-salon-frontend && npm run build",
  "mkdir -p BeautySalonAPI/wwwroot",
  "cp -r beauty-salon-frontend/build/. BeautySalonAPI/wwwroot/",
  "cd BeautySalonAPI && dotnet publish --configuration Release -o out"
]

[start]
cmd = "cd BeautySalonAPI/out && dotnet BeautySalonAPI.dll"
